### ISSUE TITLE
Domain name ownership

### ISSUE THREAD

**Issue by necolas** [h5bp/html5boilerplate.com-mobile#1]
Who owns mobileboilerplate.com? This is the only thing holding back the deployment of this site and the HTML5 Boilerplate release (because the mobile project needs a site before we redirect html5boilerplate.com/mobile there). We need to find out ASAP.

If we can't establish who owns it (assuming it's someone on the h5bp team), then we're going to have to buy a domain.

**Comment by alexgibson** [comment]
Not me - perhaps @shichuan?

**Comment by necolas** [comment]
Haven't heard from Shi for ages. Even if he does own it, we might have to get a different domain simply to avoid a situation like this.

**Comment by necolas** [comment]
@shichuan ?

**Comment by alrra** [comment]
The [mobileboilerplate.com](http://mobileboilerplate.com) domain name expired (via [twitter](https://twitter.com/sandprickle/status/457562365936934912))!

![](https://cloud.githubusercontent.com/assets/1223565/2749064/002fbe9e-c7e9-11e3-8008-0a3aeca9f889.png)

Cc: @alexgibson, @drublic, @necolas, @mathiasbynens

**Comment by alexgibson** [comment]
Did we ever find out who owned the domain?

**Comment by alrra** [comment]
> Did we ever find out who owned the domain ?

@alexgibson No.

**Comment by alexgibson** [comment]
I'm guessing @shichuan owned it, but he's not around any more and no longer seems to participate to the project. Maybe we just let it go? :(

http://html5boilerplate.com/mobile/ redirect is still working.

**Comment by alexgibson** [comment]
I've updated links in the MBP docs and readme to point to html5boilerplate.com/mobile/ for the time being. I can't seem to edit the repo description though, which I don't have access to.

**Comment by drublic** [comment]
>  I can't seem to edit the repo description though, which I don't have access to.

I've updated it.

Anyone interested in registering this domain via their GoDaddy account? I am not a customer yet, so I don't want to buy.

**Comment by alrra** [comment]
> I am not a customer yet, so I don't want to buy.

+1 :)

**Comment by alrra** [comment]
Someone registered http://mobileboilerplate.com/.
