### ISSUE TITLE
Merge the content of this repository into `html5boilerplate.com`

### ISSUE THREAD

**Issue by alrra** [h5bp/html5boilerplate.com-mobile#10]
Previous discussion: https://github.com/h5bp/html5boilerplate.com/issues/108.
## 

These days this repository is basically [mirroring the changes from](https://github.com/h5bp/html5boilerplate.com-mobile/issues/9) the [h5bp/html5boilerplate.com](https://github.com/h5bp/html5boilerplate.com) repository, thus, duplicating the effort. 

Cc: @h5bp/html5boilerplate-com-mobile, @h5bp/owners

**Comment by arthurvr** [comment]
Definitely a +1 of mine. Having to deal with 2 separated repos containing nearly the same stuff is hard.

**Comment by arthurvr** [comment]
Closing this as mobile-boilerplate is deprecated and as a result this is not needed anymore.
