### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by alrra** [h5bp/html5boilerplate.com-mobile#5]
Since [we don't own](https://github.com/h5bp/mobileboilerplate.com/issues/1) the http://mobileboilerplate.com/ domain (nor is it redirecting to http://html5boilerplate.com/mobile/), I think we should rename this repository to something like `html5boilerplate.com-mobile`.

Cc: @h5bp/owners @alexgibson

**Comment by alexgibson** [comment]
Agree it should be renamed :+1:

**Comment by mathiasbynens** [comment]
Absolutely. :+1:

**Comment by alrra** [comment]
- [x] Rename repository
- [x] Update git remotes on server
- [x] Update [related documentation](https://github.com/h5bp/html5boilerplate.com/wiki)
